gText_Birch_Welcome::
	.string "Hello!\n"
	.string "I'm Hatsune Miku.\l"
	.string "But you can just call me Miku.\p"

	.string "Welcome to ???,\n"
	.string "The world of vocal synthesizers.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Here is one\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Am I a vocal synthesizer?\p"
	.string "No silly! I'm a real person.\p"
	.string "Just like you :)\p"
	.string "But you seem like more than just a normal\n"
	.string "person.\p"
	.string "You seem like a music producer!\p"
	.string "Let me get you registered so you can\n"
	.string "start making music!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "$"

gText_Birch_BoyOrGirl::
	.string "What's your favorite color?\l"
	.string "I won't judge you :)$"

gText_Birch_WhatsYourName::
	.string "I see...\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're all set up now!\p"
	.string "You'll be moving to the town of\n"
	.string "LITTLEROOT\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Good luck!\p"
	.string "$"
